### ISSUE TITLE
Mark as virtual

### ISSUE THREAD

**Issue by beardordie** [VeryHotShark/First-Person-Controller-VeryHotShark#1]
For all classes can you please add the virtual keyword to all methods, and for any methods that are marked private or private by default can you change to protected? This will open up the system to extension and modification via inheritance and polymorphism. Thanks!

**Comment by VeryHotShark** [comment]
I will my friend, im just really busy right now but in next week i will try to do it :)

**Comment by VeryHotShark** [comment]
I had to revert this commit because i had some merge issue and i wanted to push my interaction system prototype so i will mark everything virtual in near future :)

**Comment by VeryHotShark** [comment]
Done
