### ISSUE TITLE
Assertion failed on expression: 'IsNormalized(direction)'

### ISSUE THREAD

**Issue by beardordie** [VeryHotShark/First-Person-Controller-VeryHotShark#3]
I was intermittently getting this error:
```
Assertion failed on expression: 'IsNormalized(direction)'
UnityEngine.Physics:SphereCast(Vector3, Single, Vector3, RaycastHit&, Single, Int32)
```

After reading Unity Forum, seems the issue is that SphereCast is expecting the direction to be normalized. So, I **_think_** it is fixed by normalizing that direction on FirstPersonController.cs. Line changed to this:
**_hitWall = Physics.SphereCast(_origin,rayObstacleSphereRadius,m_smoothFinalMoveDir.normalized, out _wallInfo,rayObstacleLength,obstacleLayers);**

**Comment by VeryHotShark** [comment]
I fixed by changing m_smoothFinalMoveDir to m_finalMoveDir since it is already normalized :) Thanks for pointing it out
