### ISSUE TITLE
Crouching during the Landing Animation causes a glitch in the tween

### ISSUE THREAD

**Issue by beardordie** [VeryHotShark/First-Person-Controller-VeryHotShark#4]
If you start to crouch during the landing animation, the tween is jarring. One solution I found is to insert this code within the HandleCrouch method:

```
if (movementInputData.CrouchClicked && m_isGrounded && m_LandRoutine != null)
{
    StopCoroutine(m_LandRoutine);
}
```

**Comment by VeryHotShark** [comment]
I fixed it by stopping landing coroutine everytime user press crouch if landing coroutine is present <3
