### ISSUE TITLE
In CamerZoom, Run FOV and Zoom FOV don't run well simultaneously

### ISSUE THREAD

**Issue by beardordie** [VeryHotShark/First-Person-Controller-VeryHotShark#5]
If you run and zoom at the same time, or one within the other, the FOV changes don't play nice together and cause a jarring tween. A solution that is working well for me is to Stop each other's Coroutines, not just their own. So in CamerZoom.cs the methods would look like this (new lines outlined in red):
![Clipboard01](https://user-images.githubusercontent.com/33188004/59987160-910fd600-95ee-11e9-8525-cf950e886d87.gif)

**Comment by VeryHotShark** [comment]
I fixed it but it's a temporary solution because it's not the nices but it works. Basically i made that you can zoom during running and zoom will stop once you start running
